app:
  name: Acme Ltd
  domain: acme.dev
  cookie_name: ipmi_auth_token
  data_dir: ./data/
  log:
    level: debug
    file: app.log
usb:
  # Path for the emulated USB HID
  hid_path: /dev/hid0
gpio:
  # GPIO pins to be used for input and output respectively
  # See https://pinout.xyz/resources/raspberry-pi-pinout.png
  inputs:
    - 2
    - 3
  outputs:
    - 27
    - 22
images:
  upload_dir: ./resources/images/
keys:
  store: mysql
  store_config:
    dsn: ipmi:password@localhost/ipmi
    raw_query: SELECT keys FROM keys_store WHERE username = ?
  server:
    public: keys/public.pem
    private: keys/private.pem
jwt:
  algorithm: ES512
  authn_timeout: 1
  session_timeout: 60
  leeway: 15
